### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by miguel-mx** [miguel-mx/PRIMA#1]
Banner
Location

**Comment by ghost** [comment]
![banner1](https://cloud.githubusercontent.com/assets/24551678/21820432/35267a4e-d735-11e6-9e4c-0063eb33edc5.png)
![banner2](https://cloud.githubusercontent.com/assets/24551678/21820433/35416110-d735-11e6-9913-9185e116e867.png)
![banneroaxaca](https://cloud.githubusercontent.com/assets/24551678/21820434/35458808-d735-11e6-85e4-60024f11daa8.png)

**Comment by miguel-mx** [comment]
Faltan los textos

**Comment by ghost** [comment]
Instituto Tecnológico de Oaxaca
Avenida Ing. Victor Bravo Ahuja no.125 Esquina Calzada Tecnológico cp 68030

**Comment by ghost** [comment]
Oaxaca (pronounced wa-hah-kah), founded in 1532, is a city located about 400km  south of Mexico City, is the capital of the state of the same name. It has a mild climate, due to its altitude of 1555m above sea level. Rich in history and culture, Oaxaca is a fascinating destination, sometimes considered "Mexico's culinary and art capital". Archeology, ancient civilizations, colonial art and architecture, can be appreciated. It is a safe city, full with vibrant cultural traditions.
